td_agent:
  aggr:
    ip: 0.0.0.0
    port: 16000
  edge:
    ip:
      gcp:   127.0.0.1
      azure: 127.0.0.1
      aws:   127.0.0.1
    port: 16000
  plugins:
    aggr:
      - { name: 'fluent-plugin-multiprocess' }
      - { name: 'fluent-plugin-secure-forward' }
    gcp:
      - { name: 'fluent-plugin-bigquery' }
      - { name: 'fluent-plugin-google-cloud' }
      - { name: 'fluent-plugin-google-cloud-storage' }
      - { name: 'fluent-plugin-gcloud-pubsub-custom' }
    aws:
      - { name: 'fluent-plugin-kinesis' }
      - { name: 'fluent-plugin-redshift' }
      - { name: 'fluent-plugin-s3' }
    azure:
      - { name: 'fluent-plugin-elasticsearch' }
      - { name: 'fluent-plugin-azurestorage' }
      - { name: 'fluent-plugin-azureeventhubs' }
  position_path: /var/log/td-agent/position
